import { vi } from 'vitest';

export const mockClient = {
  clientId: 'app_test123',
  clientSecret: 'secret_test',
  accessToken: null,
  refreshToken: null,
  get: vi.fn(),
  post: vi.fn(),
  patch: vi.fn(),
  delete: vi.fn(),
  setSession: vi.fn(),
  clearSession: vi.fn(),
  isAuthenticated: vi.fn(() => false),
  getCurrentUser: vi.fn(() => null),
};

vi.mock('../src/config/client.js', () => ({
  default: mockClient,
}));

vi.mock('voult-sdk', () => ({
  VoultClient: vi.fn(),
  signUpWithEmailAndPassword: vi.fn(),
  signUpWithUsernameAndPassword: vi.fn(),
  signInWithEmailAndPassword: vi.fn(),
  signInWithUsernameAndPassword: vi.fn(),
  signInWithEmailLink: vi.fn(),
  verifyEmailLink: vi.fn(),
  signOut: vi.fn(),
  deleteUser: vi.fn(),
  getCurrentUser: vi.fn(),
  updateProfile: vi.fn(),
  reenableAccount: vi.fn(),
  sendPasswordResetEmail: vi.fn(),
  resetPassword: vi.fn(),
  verifyEmail: vi.fn(),
  refreshSession: vi.fn(),
  listSessions: vi.fn(),
  revokeSession: vi.fn(),
  verifyMfaLogin: vi.fn(),
  getMfaStatus: vi.fn(),
  setupMfa: vi.fn(),
  enableMfa: vi.fn(),
  disableMfa: vi.fn(),
  regenerateMfaBackupCodes: vi.fn(),
  getWebAuthnCompatibility: vi.fn(),
  createPasskeyRegistrationOptions: vi.fn(),
  verifyPasskeyRegistration: vi.fn(),
  createPasskeyLoginOptions: vi.fn(),
  verifyPasskeyLogin: vi.fn(),
  listPasskeys: vi.fn(),
  updatePasskey: vi.fn(),
  deletePasskey: vi.fn(),
  signInWithGoogle: vi.fn(),
  signUpWithGoogle: vi.fn(),
  authenticateWithGoogle: vi.fn(),
  signInWithGitHub: vi.fn(),
  signUpWithGitHub: vi.fn(),
  authenticateWithGitHub: vi.fn(),
  signInWithFacebook: vi.fn(),
  signUpWithFacebook: vi.fn(),
  authenticateWithFacebook: vi.fn(),
  signInWithLinkedIn: vi.fn(),
  signUpWithLinkedIn: vi.fn(),
  authenticateWithLinkedIn: vi.fn(),
  signInWithMicrosoft: vi.fn(),
  signUpWithMicrosoft: vi.fn(),
  authenticateWithMicrosoft: vi.fn(),
  signInWithApple: vi.fn(),
  signUpWithApple: vi.fn(),
  authenticateWithApple: vi.fn(),
  getOAuthAuthorizationUrl: vi.fn(),
  exchangeOAuthCode: vi.fn(),
  linkOAuthProvider: vi.fn(),
  getLinkedOAuthProviders: vi.fn(),
  unlinkOAuthProvider: vi.fn(),
  setPassword: vi.fn(),
}));
